//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.0
//     from Assets/Scripts/KeyboardInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Scripts/KeyboardInput.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @KeyboardInput: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @KeyboardInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""KeyboardInput"",
    ""maps"": [
        {
            ""name"": ""PianoKeys"",
            ""id"": ""a2032625-addc-44a8-9e31-2434a3c69bc9"",
            ""actions"": [
                {
                    ""name"": ""2C"",
                    ""type"": ""Button"",
                    ""id"": ""6c3bb383-96dd-4e4f-abdd-8b9336eda4b6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""2Csharp"",
                    ""type"": ""Button"",
                    ""id"": ""64a24e81-8e61-4424-9a33-45c7b861d46d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""2D"",
                    ""type"": ""Button"",
                    ""id"": ""5f261ad3-e28c-4370-b0eb-240c58641d23"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""2Dsharp"",
                    ""type"": ""Button"",
                    ""id"": ""a3c42642-783a-4554-9910-6d6f2a2863c7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""2E"",
                    ""type"": ""Button"",
                    ""id"": ""922cd9e5-788f-41f5-a516-e13c0ba69f0e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""2F"",
                    ""type"": ""Button"",
                    ""id"": ""a143ac7c-b660-40af-96f9-1c34f614a0cf"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""2Fsharp"",
                    ""type"": ""Button"",
                    ""id"": ""fc59aa7d-6893-4c8f-b1fc-f407fd66a0a0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""2G"",
                    ""type"": ""Button"",
                    ""id"": ""aa27208d-43de-44d5-9fc0-dba0d3a7e42e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""2Gsharp"",
                    ""type"": ""Button"",
                    ""id"": ""15a13adf-05e7-49ab-b55a-6e12f06a84a8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""2A"",
                    ""type"": ""Button"",
                    ""id"": ""6675c521-4132-44ce-8b71-e5192a1b1598"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""2Asharp"",
                    ""type"": ""Button"",
                    ""id"": ""3ff6e219-4473-4216-8c73-afd8ae315b16"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""2B"",
                    ""type"": ""Button"",
                    ""id"": ""9690b767-a5fd-4621-94f9-0374d570bc85"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""3C"",
                    ""type"": ""Button"",
                    ""id"": ""04255173-641c-4fa2-a2aa-1825ce308539"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""3Csharp"",
                    ""type"": ""Button"",
                    ""id"": ""e8f04f31-d48d-44ae-8ce3-29fcf07cd009"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""3D"",
                    ""type"": ""Button"",
                    ""id"": ""bf8c6e36-58e8-4964-ac91-23a5daae43eb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""3Dsharp"",
                    ""type"": ""Button"",
                    ""id"": ""0316b55e-1cdc-470f-af23-ddbe48866e90"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""3E"",
                    ""type"": ""Button"",
                    ""id"": ""8b267ba7-afc5-4c10-9519-b1ff8472e23a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""3F"",
                    ""type"": ""Button"",
                    ""id"": ""f11dbf32-da83-4c52-be9e-951fcf804c8d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""3Fsharp"",
                    ""type"": ""Button"",
                    ""id"": ""30d47afa-5c79-4827-acb0-c21925930660"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""3G"",
                    ""type"": ""Button"",
                    ""id"": ""ab65022c-9237-4e8d-b798-bfddaa397e6c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""3Gsharp"",
                    ""type"": ""Button"",
                    ""id"": ""bfb67283-e360-43b9-8734-85351cf96a9d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""3A"",
                    ""type"": ""Button"",
                    ""id"": ""a8d799fb-2aae-4435-9309-5e69ce1ce154"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""3Asharp"",
                    ""type"": ""Button"",
                    ""id"": ""a1595222-7c06-4bfa-8be5-f5f791f64522"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""3B"",
                    ""type"": ""Button"",
                    ""id"": ""71ee5e4e-ab86-4ed0-8de1-41e56b46fbfd"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""4C"",
                    ""type"": ""Button"",
                    ""id"": ""42584843-63fa-4c3a-9026-5d802437cf06"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8c98770f-e07a-4f7a-b165-82895b37ca3f"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""2C"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b26ff2b4-b70c-46be-9a6b-d45463ef28c0"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""2Csharp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8bcfe9b0-bcad-4e1b-86ae-67728c163daa"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""2D"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""95fc0451-b7eb-4c5f-9a70-6fa175948e28"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""2Dsharp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cbb7e321-d05e-4a5d-9ac2-516761ab8c9e"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""2E"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2d1e59a7-e9fd-4bf9-9898-71869ed3c330"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""2F"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2387c733-6ebb-4e5c-96d2-a24d94b01711"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""2Fsharp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cde6c6ea-42d2-46a4-bdbb-c14067211b69"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""2G"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""92482198-ba14-4116-8f7a-95d610ce8fbb"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""2Gsharp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""54231eb3-b7b4-4446-8247-f03793876ad3"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""2A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1e8b24ce-7b6b-40bb-88cb-8d293548a8d5"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""2Asharp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""60b67d3d-a743-4140-b4b1-ed23a77e8f12"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""2B"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""431e9218-e925-4ece-a40b-4bd7feaec83e"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""3C"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fc58e15d-a208-4f25-b5a6-79d68995246c"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""3Csharp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""11155b66-971c-4255-a71f-2e1705226a1e"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""3D"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""873edcb7-bc6c-4795-bc37-3e736430049e"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""3Dsharp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9dba9cb7-e733-4c13-a43c-a7ff33045ace"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""3E"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""91c21563-3cb0-4997-83fd-ab92cd051755"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""3F"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a94b693-9970-4d4d-9380-74d68953dff2"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""3Fsharp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""df1eef70-0c5a-486c-b11e-0f97907cd2f8"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""3G"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""429960a0-b614-4425-ba4c-88248681151b"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""3Gsharp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9500782d-e27f-46a4-afba-75e6e44d383e"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""3A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b5a82e08-6bce-42db-bebf-be6d333e5cce"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""3Asharp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ee7957b6-2c4b-42b9-98b4-fcfc8e6ffabc"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""3B"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f87b53e6-6b0d-41ac-9882-b156029f80f8"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""4C"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PianoKeys
        m_PianoKeys = asset.FindActionMap("PianoKeys", throwIfNotFound: true);
        m_PianoKeys__2C = m_PianoKeys.FindAction("2C", throwIfNotFound: true);
        m_PianoKeys__2Csharp = m_PianoKeys.FindAction("2Csharp", throwIfNotFound: true);
        m_PianoKeys__2D = m_PianoKeys.FindAction("2D", throwIfNotFound: true);
        m_PianoKeys__2Dsharp = m_PianoKeys.FindAction("2Dsharp", throwIfNotFound: true);
        m_PianoKeys__2E = m_PianoKeys.FindAction("2E", throwIfNotFound: true);
        m_PianoKeys__2F = m_PianoKeys.FindAction("2F", throwIfNotFound: true);
        m_PianoKeys__2Fsharp = m_PianoKeys.FindAction("2Fsharp", throwIfNotFound: true);
        m_PianoKeys__2G = m_PianoKeys.FindAction("2G", throwIfNotFound: true);
        m_PianoKeys__2Gsharp = m_PianoKeys.FindAction("2Gsharp", throwIfNotFound: true);
        m_PianoKeys__2A = m_PianoKeys.FindAction("2A", throwIfNotFound: true);
        m_PianoKeys__2Asharp = m_PianoKeys.FindAction("2Asharp", throwIfNotFound: true);
        m_PianoKeys__2B = m_PianoKeys.FindAction("2B", throwIfNotFound: true);
        m_PianoKeys__3C = m_PianoKeys.FindAction("3C", throwIfNotFound: true);
        m_PianoKeys__3Csharp = m_PianoKeys.FindAction("3Csharp", throwIfNotFound: true);
        m_PianoKeys__3D = m_PianoKeys.FindAction("3D", throwIfNotFound: true);
        m_PianoKeys__3Dsharp = m_PianoKeys.FindAction("3Dsharp", throwIfNotFound: true);
        m_PianoKeys__3E = m_PianoKeys.FindAction("3E", throwIfNotFound: true);
        m_PianoKeys__3F = m_PianoKeys.FindAction("3F", throwIfNotFound: true);
        m_PianoKeys__3Fsharp = m_PianoKeys.FindAction("3Fsharp", throwIfNotFound: true);
        m_PianoKeys__3G = m_PianoKeys.FindAction("3G", throwIfNotFound: true);
        m_PianoKeys__3Gsharp = m_PianoKeys.FindAction("3Gsharp", throwIfNotFound: true);
        m_PianoKeys__3A = m_PianoKeys.FindAction("3A", throwIfNotFound: true);
        m_PianoKeys__3Asharp = m_PianoKeys.FindAction("3Asharp", throwIfNotFound: true);
        m_PianoKeys__3B = m_PianoKeys.FindAction("3B", throwIfNotFound: true);
        m_PianoKeys__4C = m_PianoKeys.FindAction("4C", throwIfNotFound: true);
    }

    ~@KeyboardInput()
    {
        UnityEngine.Debug.Assert(!m_PianoKeys.enabled, "This will cause a leak and performance issues, KeyboardInput.PianoKeys.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PianoKeys
    private readonly InputActionMap m_PianoKeys;
    private List<IPianoKeysActions> m_PianoKeysActionsCallbackInterfaces = new List<IPianoKeysActions>();
    private readonly InputAction m_PianoKeys__2C;
    private readonly InputAction m_PianoKeys__2Csharp;
    private readonly InputAction m_PianoKeys__2D;
    private readonly InputAction m_PianoKeys__2Dsharp;
    private readonly InputAction m_PianoKeys__2E;
    private readonly InputAction m_PianoKeys__2F;
    private readonly InputAction m_PianoKeys__2Fsharp;
    private readonly InputAction m_PianoKeys__2G;
    private readonly InputAction m_PianoKeys__2Gsharp;
    private readonly InputAction m_PianoKeys__2A;
    private readonly InputAction m_PianoKeys__2Asharp;
    private readonly InputAction m_PianoKeys__2B;
    private readonly InputAction m_PianoKeys__3C;
    private readonly InputAction m_PianoKeys__3Csharp;
    private readonly InputAction m_PianoKeys__3D;
    private readonly InputAction m_PianoKeys__3Dsharp;
    private readonly InputAction m_PianoKeys__3E;
    private readonly InputAction m_PianoKeys__3F;
    private readonly InputAction m_PianoKeys__3Fsharp;
    private readonly InputAction m_PianoKeys__3G;
    private readonly InputAction m_PianoKeys__3Gsharp;
    private readonly InputAction m_PianoKeys__3A;
    private readonly InputAction m_PianoKeys__3Asharp;
    private readonly InputAction m_PianoKeys__3B;
    private readonly InputAction m_PianoKeys__4C;
    /// <summary>
    /// Provides access to input actions defined in input action map "PianoKeys".
    /// </summary>
    public struct PianoKeysActions
    {
        private @KeyboardInput m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PianoKeysActions(@KeyboardInput wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "PianoKeys/_2C".
        /// </summary>
        public InputAction @_2C => m_Wrapper.m_PianoKeys__2C;
        /// <summary>
        /// Provides access to the underlying input action "PianoKeys/_2Csharp".
        /// </summary>
        public InputAction @_2Csharp => m_Wrapper.m_PianoKeys__2Csharp;
        /// <summary>
        /// Provides access to the underlying input action "PianoKeys/_2D".
        /// </summary>
        public InputAction @_2D => m_Wrapper.m_PianoKeys__2D;
        /// <summary>
        /// Provides access to the underlying input action "PianoKeys/_2Dsharp".
        /// </summary>
        public InputAction @_2Dsharp => m_Wrapper.m_PianoKeys__2Dsharp;
        /// <summary>
        /// Provides access to the underlying input action "PianoKeys/_2E".
        /// </summary>
        public InputAction @_2E => m_Wrapper.m_PianoKeys__2E;
        /// <summary>
        /// Provides access to the underlying input action "PianoKeys/_2F".
        /// </summary>
        public InputAction @_2F => m_Wrapper.m_PianoKeys__2F;
        /// <summary>
        /// Provides access to the underlying input action "PianoKeys/_2Fsharp".
        /// </summary>
        public InputAction @_2Fsharp => m_Wrapper.m_PianoKeys__2Fsharp;
        /// <summary>
        /// Provides access to the underlying input action "PianoKeys/_2G".
        /// </summary>
        public InputAction @_2G => m_Wrapper.m_PianoKeys__2G;
        /// <summary>
        /// Provides access to the underlying input action "PianoKeys/_2Gsharp".
        /// </summary>
        public InputAction @_2Gsharp => m_Wrapper.m_PianoKeys__2Gsharp;
        /// <summary>
        /// Provides access to the underlying input action "PianoKeys/_2A".
        /// </summary>
        public InputAction @_2A => m_Wrapper.m_PianoKeys__2A;
        /// <summary>
        /// Provides access to the underlying input action "PianoKeys/_2Asharp".
        /// </summary>
        public InputAction @_2Asharp => m_Wrapper.m_PianoKeys__2Asharp;
        /// <summary>
        /// Provides access to the underlying input action "PianoKeys/_2B".
        /// </summary>
        public InputAction @_2B => m_Wrapper.m_PianoKeys__2B;
        /// <summary>
        /// Provides access to the underlying input action "PianoKeys/_3C".
        /// </summary>
        public InputAction @_3C => m_Wrapper.m_PianoKeys__3C;
        /// <summary>
        /// Provides access to the underlying input action "PianoKeys/_3Csharp".
        /// </summary>
        public InputAction @_3Csharp => m_Wrapper.m_PianoKeys__3Csharp;
        /// <summary>
        /// Provides access to the underlying input action "PianoKeys/_3D".
        /// </summary>
        public InputAction @_3D => m_Wrapper.m_PianoKeys__3D;
        /// <summary>
        /// Provides access to the underlying input action "PianoKeys/_3Dsharp".
        /// </summary>
        public InputAction @_3Dsharp => m_Wrapper.m_PianoKeys__3Dsharp;
        /// <summary>
        /// Provides access to the underlying input action "PianoKeys/_3E".
        /// </summary>
        public InputAction @_3E => m_Wrapper.m_PianoKeys__3E;
        /// <summary>
        /// Provides access to the underlying input action "PianoKeys/_3F".
        /// </summary>
        public InputAction @_3F => m_Wrapper.m_PianoKeys__3F;
        /// <summary>
        /// Provides access to the underlying input action "PianoKeys/_3Fsharp".
        /// </summary>
        public InputAction @_3Fsharp => m_Wrapper.m_PianoKeys__3Fsharp;
        /// <summary>
        /// Provides access to the underlying input action "PianoKeys/_3G".
        /// </summary>
        public InputAction @_3G => m_Wrapper.m_PianoKeys__3G;
        /// <summary>
        /// Provides access to the underlying input action "PianoKeys/_3Gsharp".
        /// </summary>
        public InputAction @_3Gsharp => m_Wrapper.m_PianoKeys__3Gsharp;
        /// <summary>
        /// Provides access to the underlying input action "PianoKeys/_3A".
        /// </summary>
        public InputAction @_3A => m_Wrapper.m_PianoKeys__3A;
        /// <summary>
        /// Provides access to the underlying input action "PianoKeys/_3Asharp".
        /// </summary>
        public InputAction @_3Asharp => m_Wrapper.m_PianoKeys__3Asharp;
        /// <summary>
        /// Provides access to the underlying input action "PianoKeys/_3B".
        /// </summary>
        public InputAction @_3B => m_Wrapper.m_PianoKeys__3B;
        /// <summary>
        /// Provides access to the underlying input action "PianoKeys/_4C".
        /// </summary>
        public InputAction @_4C => m_Wrapper.m_PianoKeys__4C;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_PianoKeys; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PianoKeysActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PianoKeysActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PianoKeysActions" />
        public void AddCallbacks(IPianoKeysActions instance)
        {
            if (instance == null || m_Wrapper.m_PianoKeysActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PianoKeysActionsCallbackInterfaces.Add(instance);
            @_2C.started += instance.On_2C;
            @_2C.performed += instance.On_2C;
            @_2C.canceled += instance.On_2C;
            @_2Csharp.started += instance.On_2Csharp;
            @_2Csharp.performed += instance.On_2Csharp;
            @_2Csharp.canceled += instance.On_2Csharp;
            @_2D.started += instance.On_2D;
            @_2D.performed += instance.On_2D;
            @_2D.canceled += instance.On_2D;
            @_2Dsharp.started += instance.On_2Dsharp;
            @_2Dsharp.performed += instance.On_2Dsharp;
            @_2Dsharp.canceled += instance.On_2Dsharp;
            @_2E.started += instance.On_2E;
            @_2E.performed += instance.On_2E;
            @_2E.canceled += instance.On_2E;
            @_2F.started += instance.On_2F;
            @_2F.performed += instance.On_2F;
            @_2F.canceled += instance.On_2F;
            @_2Fsharp.started += instance.On_2Fsharp;
            @_2Fsharp.performed += instance.On_2Fsharp;
            @_2Fsharp.canceled += instance.On_2Fsharp;
            @_2G.started += instance.On_2G;
            @_2G.performed += instance.On_2G;
            @_2G.canceled += instance.On_2G;
            @_2Gsharp.started += instance.On_2Gsharp;
            @_2Gsharp.performed += instance.On_2Gsharp;
            @_2Gsharp.canceled += instance.On_2Gsharp;
            @_2A.started += instance.On_2A;
            @_2A.performed += instance.On_2A;
            @_2A.canceled += instance.On_2A;
            @_2Asharp.started += instance.On_2Asharp;
            @_2Asharp.performed += instance.On_2Asharp;
            @_2Asharp.canceled += instance.On_2Asharp;
            @_2B.started += instance.On_2B;
            @_2B.performed += instance.On_2B;
            @_2B.canceled += instance.On_2B;
            @_3C.started += instance.On_3C;
            @_3C.performed += instance.On_3C;
            @_3C.canceled += instance.On_3C;
            @_3Csharp.started += instance.On_3Csharp;
            @_3Csharp.performed += instance.On_3Csharp;
            @_3Csharp.canceled += instance.On_3Csharp;
            @_3D.started += instance.On_3D;
            @_3D.performed += instance.On_3D;
            @_3D.canceled += instance.On_3D;
            @_3Dsharp.started += instance.On_3Dsharp;
            @_3Dsharp.performed += instance.On_3Dsharp;
            @_3Dsharp.canceled += instance.On_3Dsharp;
            @_3E.started += instance.On_3E;
            @_3E.performed += instance.On_3E;
            @_3E.canceled += instance.On_3E;
            @_3F.started += instance.On_3F;
            @_3F.performed += instance.On_3F;
            @_3F.canceled += instance.On_3F;
            @_3Fsharp.started += instance.On_3Fsharp;
            @_3Fsharp.performed += instance.On_3Fsharp;
            @_3Fsharp.canceled += instance.On_3Fsharp;
            @_3G.started += instance.On_3G;
            @_3G.performed += instance.On_3G;
            @_3G.canceled += instance.On_3G;
            @_3Gsharp.started += instance.On_3Gsharp;
            @_3Gsharp.performed += instance.On_3Gsharp;
            @_3Gsharp.canceled += instance.On_3Gsharp;
            @_3A.started += instance.On_3A;
            @_3A.performed += instance.On_3A;
            @_3A.canceled += instance.On_3A;
            @_3Asharp.started += instance.On_3Asharp;
            @_3Asharp.performed += instance.On_3Asharp;
            @_3Asharp.canceled += instance.On_3Asharp;
            @_3B.started += instance.On_3B;
            @_3B.performed += instance.On_3B;
            @_3B.canceled += instance.On_3B;
            @_4C.started += instance.On_4C;
            @_4C.performed += instance.On_4C;
            @_4C.canceled += instance.On_4C;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PianoKeysActions" />
        private void UnregisterCallbacks(IPianoKeysActions instance)
        {
            @_2C.started -= instance.On_2C;
            @_2C.performed -= instance.On_2C;
            @_2C.canceled -= instance.On_2C;
            @_2Csharp.started -= instance.On_2Csharp;
            @_2Csharp.performed -= instance.On_2Csharp;
            @_2Csharp.canceled -= instance.On_2Csharp;
            @_2D.started -= instance.On_2D;
            @_2D.performed -= instance.On_2D;
            @_2D.canceled -= instance.On_2D;
            @_2Dsharp.started -= instance.On_2Dsharp;
            @_2Dsharp.performed -= instance.On_2Dsharp;
            @_2Dsharp.canceled -= instance.On_2Dsharp;
            @_2E.started -= instance.On_2E;
            @_2E.performed -= instance.On_2E;
            @_2E.canceled -= instance.On_2E;
            @_2F.started -= instance.On_2F;
            @_2F.performed -= instance.On_2F;
            @_2F.canceled -= instance.On_2F;
            @_2Fsharp.started -= instance.On_2Fsharp;
            @_2Fsharp.performed -= instance.On_2Fsharp;
            @_2Fsharp.canceled -= instance.On_2Fsharp;
            @_2G.started -= instance.On_2G;
            @_2G.performed -= instance.On_2G;
            @_2G.canceled -= instance.On_2G;
            @_2Gsharp.started -= instance.On_2Gsharp;
            @_2Gsharp.performed -= instance.On_2Gsharp;
            @_2Gsharp.canceled -= instance.On_2Gsharp;
            @_2A.started -= instance.On_2A;
            @_2A.performed -= instance.On_2A;
            @_2A.canceled -= instance.On_2A;
            @_2Asharp.started -= instance.On_2Asharp;
            @_2Asharp.performed -= instance.On_2Asharp;
            @_2Asharp.canceled -= instance.On_2Asharp;
            @_2B.started -= instance.On_2B;
            @_2B.performed -= instance.On_2B;
            @_2B.canceled -= instance.On_2B;
            @_3C.started -= instance.On_3C;
            @_3C.performed -= instance.On_3C;
            @_3C.canceled -= instance.On_3C;
            @_3Csharp.started -= instance.On_3Csharp;
            @_3Csharp.performed -= instance.On_3Csharp;
            @_3Csharp.canceled -= instance.On_3Csharp;
            @_3D.started -= instance.On_3D;
            @_3D.performed -= instance.On_3D;
            @_3D.canceled -= instance.On_3D;
            @_3Dsharp.started -= instance.On_3Dsharp;
            @_3Dsharp.performed -= instance.On_3Dsharp;
            @_3Dsharp.canceled -= instance.On_3Dsharp;
            @_3E.started -= instance.On_3E;
            @_3E.performed -= instance.On_3E;
            @_3E.canceled -= instance.On_3E;
            @_3F.started -= instance.On_3F;
            @_3F.performed -= instance.On_3F;
            @_3F.canceled -= instance.On_3F;
            @_3Fsharp.started -= instance.On_3Fsharp;
            @_3Fsharp.performed -= instance.On_3Fsharp;
            @_3Fsharp.canceled -= instance.On_3Fsharp;
            @_3G.started -= instance.On_3G;
            @_3G.performed -= instance.On_3G;
            @_3G.canceled -= instance.On_3G;
            @_3Gsharp.started -= instance.On_3Gsharp;
            @_3Gsharp.performed -= instance.On_3Gsharp;
            @_3Gsharp.canceled -= instance.On_3Gsharp;
            @_3A.started -= instance.On_3A;
            @_3A.performed -= instance.On_3A;
            @_3A.canceled -= instance.On_3A;
            @_3Asharp.started -= instance.On_3Asharp;
            @_3Asharp.performed -= instance.On_3Asharp;
            @_3Asharp.canceled -= instance.On_3Asharp;
            @_3B.started -= instance.On_3B;
            @_3B.performed -= instance.On_3B;
            @_3B.canceled -= instance.On_3B;
            @_4C.started -= instance.On_4C;
            @_4C.performed -= instance.On_4C;
            @_4C.canceled -= instance.On_4C;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PianoKeysActions.UnregisterCallbacks(IPianoKeysActions)" />.
        /// </summary>
        /// <seealso cref="PianoKeysActions.UnregisterCallbacks(IPianoKeysActions)" />
        public void RemoveCallbacks(IPianoKeysActions instance)
        {
            if (m_Wrapper.m_PianoKeysActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PianoKeysActions.AddCallbacks(IPianoKeysActions)" />
        /// <seealso cref="PianoKeysActions.RemoveCallbacks(IPianoKeysActions)" />
        /// <seealso cref="PianoKeysActions.UnregisterCallbacks(IPianoKeysActions)" />
        public void SetCallbacks(IPianoKeysActions instance)
        {
            foreach (var item in m_Wrapper.m_PianoKeysActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PianoKeysActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PianoKeysActions" /> instance referencing this action map.
    /// </summary>
    public PianoKeysActions @PianoKeys => new PianoKeysActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "PianoKeys" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PianoKeysActions.AddCallbacks(IPianoKeysActions)" />
    /// <seealso cref="PianoKeysActions.RemoveCallbacks(IPianoKeysActions)" />
    public interface IPianoKeysActions
    {
        /// <summary>
        /// Method invoked when associated input action "2C" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On_2C(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "2Csharp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On_2Csharp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "2D" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On_2D(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "2Dsharp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On_2Dsharp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "2E" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On_2E(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "2F" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On_2F(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "2Fsharp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On_2Fsharp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "2G" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On_2G(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "2Gsharp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On_2Gsharp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "2A" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On_2A(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "2Asharp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On_2Asharp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "2B" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On_2B(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "3C" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On_3C(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "3Csharp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On_3Csharp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "3D" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On_3D(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "3Dsharp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On_3Dsharp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "3E" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On_3E(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "3F" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On_3F(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "3Fsharp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On_3Fsharp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "3G" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On_3G(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "3Gsharp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On_3Gsharp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "3A" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On_3A(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "3Asharp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On_3Asharp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "3B" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On_3B(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "4C" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void On_4C(InputAction.CallbackContext context);
    }
}
